version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Compile stylesheets; build docs

workflows:
  build_test_release:
    jobs:
      - build_and_test
      - release:
          requires:
            - build_and_test
          filters:
            branches:
              only: main


