version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  lint_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "Test"
          command: npm run test

workflows:
  build-and-test:
    jobs:
      - be_kind_to_your_colleagues:
          type: approval
          filters:
            branches:
              ignore:
                - main
      - lint_and_test:
          requires:
            - be_kind_to_your_colleagues