version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "Test"
          command: npm run test
