version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    resource_class: small
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Compile stylesheets; build docs

workflows:
  build_test_release:
    jobs:
      - be_kind_to_your_colleagues:
          type: approval
          filters:
            branches:
              ignore:
                - main
      - build_and_test:
          requires:
            - be_kind_to_your_colleagues
      # - release:
          # requires:
          #   - build_and_test
          # filters:
          #   branches:
          #     only: main


